### Dodanie nowego zwierzęcia
POST http://localhost:4000/api/animals
Content-Type: application/json

{
  "id": "1",
  "name": "Simba",
  "species": "Scarab",
  "age": 12,
  "location": "Desert",
  "status": "READY"
}

### Pobranie listy wszystkich zwierząt
GET http://localhost:4000/api/animals

### Edycja informacji o zwierzęciu
PUT http://localhost:4000/api/animals/1
Content-Type: application/json

{
  "id": "000",
  "name": "Shibai",
  "species": "Unknown",
  "age": 10000000,
  "location": "Outer Spaces",
  "status": "Unknown"
}

### Usunięcie zwierzęcia
DELETE http://localhost:4000/api/animals/1
